In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('F:\kutty\severeinjury1.csv',encoding='cp1252')


In [3]:

import nltk

In [4]:
from nltk.util import ngrams

In [5]:
from nltk.tokenize import WhitespaceTokenizer

In [6]:
from nltk.stem.snowball import SnowballStemmer
stemming = SnowballStemmer("english")

In [7]:
data["narrative"]= data["title.new"]+data["summary.new"]

In [8]:
def identify_tokens(row):
    summary_title = row["narrative"]
    tokens = nltk.word_tokenize(summary_title)
    token_words = ngrams(tokens,3)
    tok = [" ".join(t) for t in token_words]
    return tok

In [9]:
data['words']= data.apply(identify_tokens,axis=1)

In [10]:

data['words']

0      [two workers are, workers are struck, are stru...
1      [foreman is fatally, is fatally crushed, fatal...
2      [employee suffers abdominal, suffers abdominal...
3      [employee 's body, 's body is, body is caught,...
4      [employee is punctured, is punctured in, punct...
5      [carpenter is injured, is injured in, injured ...
6      [pipeline worker is, worker is struck, is stru...
7      [employee crushes leg, crushes leg suffers, le...
8      [worker falls from, falls from roof, from roof...
9      [driver hurt when, hurt when truck, when truck...
10     [tile setter sustains, setter sustains injurie...
11     [crane operator incurs, operator incurs knee, ...
12     [employee is killed, is killed in, killed in f...
13     [employee killed in, killed in fall, in fall f...
14     [employee killed in, killed in fall, in fall f...
15     [employee 's thigh, 's thigh lacerated, thigh ...
16     [asphyxiated in rail, in rail car, rail car ;,...
17     [employee killed in, kil

In [11]:

def stem_list(row):
    my_list = row['words']
    stemmed_list = [stemming.stem(word) for word in my_list]
    return(stemmed_list)

data['stemmed_words'] = data.apply(stem_list, axis=1)

In [12]:
data['stemmed_words']

0      [two workers ar, workers are struck, are struc...
1      [foreman is fat, is fatally crush, fatally cru...
2      [employee suffers abdomin, suffers abdominal f...
3      [employee 's bodi, s body i, body is caught, i...
4      [employee is punctur, is punctured in, punctur...
5      [carpenter is injur, is injured in, injured in...
6      [pipeline worker i, worker is struck, is struc...
7      [employee crushes leg, crushes leg suff, leg s...
8      [worker falls from, falls from roof, from roof...
9      [driver hurt when, hurt when truck, when truck...
10     [tile setter sustain, setter sustains injuri, ...
11     [crane operator incur, operator incurs kne, in...
12     [employee is kil, is killed in, killed in fal,...
13     [employee killed in, killed in fal, in fall fr...
14     [employee killed in, killed in fal, in fall fr...
15     [employee 's thigh, s thigh lacer, thigh lacer...
16     [asphyxiated in rail, in rail car, rail car ;,...
17     [employee killed in, kil

In [13]:

from nltk.corpus import stopwords
stops = set(stopwords.words("english"))                  

def remove_stops(row):
    my_list = row['stemmed_words']
    meaningful_words = [w for w in my_list if not w in stops]
    return (meaningful_words)

data['stem_meaningful'] = data.apply(remove_stops, axis=1)

In [14]:

data['stem_meaningful']

0      [two workers ar, workers are struck, are struc...
1      [foreman is fat, is fatally crush, fatally cru...
2      [employee suffers abdomin, suffers abdominal f...
3      [employee 's bodi, s body i, body is caught, i...
4      [employee is punctur, is punctured in, punctur...
5      [carpenter is injur, is injured in, injured in...
6      [pipeline worker i, worker is struck, is struc...
7      [employee crushes leg, crushes leg suff, leg s...
8      [worker falls from, falls from roof, from roof...
9      [driver hurt when, hurt when truck, when truck...
10     [tile setter sustain, setter sustains injuri, ...
11     [crane operator incur, operator incurs kne, in...
12     [employee is kil, is killed in, killed in fal,...
13     [employee killed in, killed in fal, in fall fr...
14     [employee killed in, killed in fal, in fall fr...
15     [employee 's thigh, s thigh lacer, thigh lacer...
16     [asphyxiated in rail, in rail car, rail car ;,...
17     [employee killed in, kil

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
import math

In [16]:
data['stem_meaningful'] = ["  ".join(review) for review in data['stem_meaningful'].values]

In [17]:
data['stem_meaningful']

0      two workers ar  workers are struck  are struck...
1      foreman is fat  is fatally crush  fatally crus...
2      employee suffers abdomin  suffers abdominal fr...
3      employee 's bodi  s body i  body is caught  is...
4      employee is punctur  is punctured in  puncture...
5      carpenter is injur  is injured in  injured in ...
6      pipeline worker i  worker is struck  is struck...
7      employee crushes leg  crushes leg suff  leg su...
8      worker falls from  falls from roof  from roof ...
9      driver hurt when  hurt when truck  when truck ...
10     tile setter sustain  setter sustains injuri  s...
11     crane operator incur  operator incurs kne  inc...
12     employee is kil  is killed in  killed in fal  ...
13     employee killed in  killed in fal  in fall fro...
14     employee killed in  killed in fal  in fall fro...
15     employee 's thigh  s thigh lacer  thigh lacera...
16     asphyxiated in rail  in rail car  rail car ;  ...
17     employee killed in  kill

In [18]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
v=TfidfVectorizer()

In [19]:
x=v.fit_transform(data['stem_meaningful'])

In [20]:
first_vector_v = x[0]

In [21]:
df = pd.DataFrame(first_vector_v.T.todense(),index = v.get_feature_names(),columns = ["tfidf"])
df.sort_values(by=["tfidf"],ascending=False)

tfidf
lane          0.263434
vehicle       0.230604
highway       0.224491
turn          0.215269
templar       0.187255
the           0.178987
struck        0.174371
travel        0.157142
and           0.141555
limit         0.136756
55            0.134965
underground   0.133290
lan           0.128831
workers       0.128687
motor         0.127499
posted        0.117821
refused       0.117821
privately     0.117821
was           0.116342
ran           0.116126
services      0.113625
veered        0.112844
next          0.112246
vehicl        0.112246
27            0.110168
along         0.109511
travelling    0.108984
marking       0.108984
emergency     0.108877
hour          0.106455
...                ...
expos         0.000000
explosive     0.000000
explosion     0.000000
explos        0.000000
exploding     0.000000
explodes      0.000000
exploded      0.000000
explode       0.000000
explod        0.000000
explained     0.000000
explain       0.000000
experiencing  0.000000
experiences   0.000000
experience    0.000000
existing      0.000000
experienc     0.000000
experi        0.000000
expelling     0.000000
expel         0.000000
expected      0.000000
expect        0.000000
expansion     0.000000
expans        0.000000
expanding     0.000000
expanded      0.000000
expand        0.000000
exiting       0.000000
exited        0.000000
exit          0.000000
zones         0.000000

[8907 rows x 1 columns]

In [22]:

from sklearn.preprocessing import LabelEncoder
from collections import defaultdict
from nltk.corpus import wordnet as wn
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import model_selection, naive_bayes,svm
from sklearn.metrics import accuracy_score

In [23]:
import numpy as np

In [24]:

Train_X, Test_X, Train_Y, Test_Y = model_selection.train_test_split(data['summary.new'],data['Tagged2'],test_size=0.2)

In [25]:
Encoder = LabelEncoder()
Train_Y = Encoder.fit_transform(Train_Y)
Test_Y = Encoder.fit_transform(Test_Y)

In [26]:
Train_X_Tfidf = v.transform(Train_X)
Test_X_Tfidf = v.transform(Test_X)

In [27]:
print(v.vocabulary_)

{u'yellow': 8893, u'interchang': 4209, u'four': 3366, u'railing': 6170, u'increase': 4054, u'electricity': 2739, u'wheeled': 8753, u'meadows': 4890, u'sinking': 7118, u'digit': 2417, u'propane': 6045, u'regional': 6358, u'foul': 3362, u'malfunctioned': 4798, u'ignit': 3964, u'bringing': 1266, u'elevations': 2757, u'disturb': 2512, u'wooden': 8834, u'piling': 5736, u'crotch': 2118, u'succession': 7656, u'path': 5604, u'nordiazepam': 5252, u'rusti': 6726, u'tired': 8063, u'miller': 4982, u'hanging': 3710, u'scrapes': 6828, u'scraper': 6826, u'tires': 8064, u'second': 6864, u'277': 180, u'scraped': 6825, u'pubis': 6086, u'milled': 4981, u'dynamit': 2676, u'contributed': 1972, u'fingers': 3210, u'replaced': 6449, u'increasing': 4056, u'shocks': 7022, u'ongo': 5378, u'misjudged': 5013, u'crouch': 2119, u'ravenel': 6213, u'splinter': 7368, u'reported': 6454, u'dorm': 2564, u'splinted': 7367, u'pancreas': 5541, u'substance': 7647, u'aug': 891, u'postop': 5884, u'climbed': 1682, u'reports': 64

In [28]:

print(Train_X_Tfidf)

  (0, 8866)	0.13872852898947638
  (0, 8857)	0.041315480241252346
  (0, 8821)	0.053612801857731665
  (0, 8788)	0.06270098025871126
  (0, 8778)	0.06983116946237235
  (0, 8776)	0.05732134493368609
  (0, 8772)	0.023544077525919645
  (0, 8769)	0.05232151407358126
  (0, 8760)	0.046365583298624426
  (0, 8741)	0.13893926497397757
  (0, 8738)	0.018030965257932897
  (0, 8736)	0.0366682577411112
  (0, 8734)	0.04434438179351785
  (0, 8726)	0.04157886896721309
  (0, 8680)	0.09945279690773544
  (0, 8630)	0.06270098025871126
  (0, 8622)	0.06270098025871126
  (0, 8516)	0.04824215320324002
  (0, 8330)	0.051370467090507674
  (0, 8198)	0.0286614297765033
  (0, 8174)	0.023381827478198648
  (0, 8148)	0.04772240029465143
  (0, 8071)	0.12143002646947967
  (0, 8009)	0.030085418218236896
  (0, 7990)	0.026600289003153258
  :	:
  (799, 2893)	0.11894674550804162
  (799, 2787)	0.10870058988740594
  (799, 2778)	0.06552982085319516
  (799, 2682)	0.09530996789258653
  (799, 2570)	0.112955558374462
  (799, 2396)	0.066

In [89]:
SVM = svm.SVC(C=0.80,kernel='linear')
SVM.fit(Train_X_Tfidf,Train_Y)

SVC(C=0.8, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [90]:

predictions_SVM = SVM.predict(Test_X_Tfidf)

In [91]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
target_names = ['Caught in/between objects','Collapse of object','Electrocution','Exposure to chemical substances','Exposure to extreme temperatures','Falls','Fires and explosions','Struck by moving objects','Struck by falling objects','Traffic','Others']

print(confusion_matrix(Test_Y,predictions_SVM))
print(classification_report(Test_Y,predictions_SVM,target_names = target_names))
print(accuracy_score(Test_Y, predictions_SVM))

[[ 3  1  0  0  0  1  0  0  0  7  1]
 [ 0 30  0  0  0  7  0  0  0  1  0]
 [ 0  1 20  0  0  0  0  0  0  0  0]
 [ 0  5  0  0  0  1  0  0  0  1  0]
 [ 0  2  0  0  0  2  0  0  0  0  0]
 [ 0 12  0  0  0 37  0  0  0  0  0]
 [ 0  4  1  0  0  1  8  0  0  1  0]
 [ 0  4  0  0  0  4  0  0  0  1  0]
 [ 0  5  0  0  0  0  0  0  0  1  0]
 [ 0  7  0  0  0  1  0  0  0 19  0]
 [ 0  4  0  0  0  0  0  0  0  2  5]]
                                  precision    recall  f1-score   support

       Caught in/between objects       1.00      0.23      0.38        13
              Collapse of object       0.40      0.79      0.53        38
                   Electrocution       0.95      0.95      0.95        21
 Exposure to chemical substances       0.00      0.00      0.00         7
Exposure to extreme temperatures       0.00      0.00      0.00         4
                           Falls       0.69      0.76      0.72        49
            Fires and explosions       1.00      0.53      0.70        15
        St

In [98]:
Naive = naive_bayes.MultinomialNB()
Naive.fit(Train_X_Tfidf,Train_Y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [99]:
predictions_NB = Naive.predict(Test_X_Tfidf)

In [100]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(Test_Y,predictions_NB))
print(classification_report(Test_Y,predictions_NB,target_names = target_names))
print(accuracy_score(Test_Y, predictions_NB))

[[ 0  5  0  0  0  8  0  0  0  0  0]
 [ 0 19  0  0  0 19  0  0  0  0  0]
 [ 0  3  4  0  0 14  0  0  0  0  0]
 [ 0  0  0  0  0  7  0  0  0  0  0]
 [ 0  1  0  0  0  3  0  0  0  0  0]
 [ 0  1  0  0  0 48  0  0  0  0  0]
 [ 0  5  0  0  0 10  0  0  0  0  0]
 [ 0  1  0  0  0  8  0  0  0  0  0]
 [ 0  6  0  0  0  0  0  0  0  0  0]
 [ 0 11  0  0  0 16  0  0  0  0  0]
 [ 0  7  0  0  0  4  0  0  0  0  0]]
                                  precision    recall  f1-score   support

       Caught in/between objects       0.00      0.00      0.00        13
              Collapse of object       0.32      0.50      0.39        38
                   Electrocution       1.00      0.19      0.32        21
 Exposure to chemical substances       0.00      0.00      0.00         7
Exposure to extreme temperatures       0.00      0.00      0.00         4
                           Falls       0.35      0.98      0.52        49
            Fires and explosions       0.00      0.00      0.00        15
        St

In [101]:
from sklearn.tree import DecisionTreeClassifier

In [102]:
clf3 = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf3.fit(Train_X_Tfidf,Train_Y)

#Predict the response for test dataset
y_pred = clf3.predict((Test_X_Tfidf))

In [103]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(Test_Y,y_pred))
print(classification_report(Test_Y,y_pred,target_names = target_names))
print(accuracy_score(Test_Y, y_pred))

[[ 8  2  0  1  0  0  0  0  1  0  1]
 [ 2 24  1  2  0  7  0  0  0  1  1]
 [ 0  0 15  1  1  1  3  0  0  0  0]
 [ 0  1  0  1  0  0  1  3  0  1  0]
 [ 0  1  0  0  0  1  1  0  0  1  0]
 [ 0 10  1  0  0 32  0  1  4  1  0]
 [ 0  1  5  0  0  0  6  1  1  1  0]
 [ 0  4  0  1  0  1  0  1  0  1  1]
 [ 0  2  0  0  0  2  0  0  2  0  0]
 [ 2  5  2  0  0  1  0  0  0 16  1]
 [ 0  2  0  1  0  1  0  0  0  2  5]]
                                  precision    recall  f1-score   support

       Caught in/between objects       0.67      0.62      0.64        13
              Collapse of object       0.46      0.63      0.53        38
                   Electrocution       0.62      0.71      0.67        21
 Exposure to chemical substances       0.14      0.14      0.14         7
Exposure to extreme temperatures       0.00      0.00      0.00         4
                           Falls       0.70      0.65      0.67        49
            Fires and explosions       0.55      0.40      0.46        15
        St

In [104]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=25)

In [105]:

classifier.fit(Train_X_Tfidf,Train_Y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=25, p=2,
           weights='uniform')

In [106]:
y_pred = classifier.predict((Test_X_Tfidf))

In [107]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(Test_Y,y_pred))
print(classification_report(Test_Y,y_pred,target_names = target_names))
print(accuracy_score(Test_Y, y_pred))

[[ 5  3  0  0  0  2  0  0  0  2  1]
 [ 0 28  0  0  0  8  0  0  0  2  0]
 [ 1  2 15  0  0  3  0  0  0  0  0]
 [ 0  2  0  0  0  4  0  0  0  1  0]
 [ 0  2  0  0  0  2  0  0  0  0  0]
 [ 0  6  0  0  0 43  0  0  0  0  0]
 [ 0  2  4  0  0  3  5  0  0  1  0]
 [ 0  2  1  0  0  5  0  0  0  1  0]
 [ 0  2  0  0  0  2  0  0  1  1  0]
 [ 3  1  1  0  0  9  0  0  0 11  2]
 [ 0  3  0  0  0  1  0  0  0  2  5]]
                                  precision    recall  f1-score   support

       Caught in/between objects       0.56      0.38      0.45        13
              Collapse of object       0.53      0.74      0.62        38
                   Electrocution       0.71      0.71      0.71        21
 Exposure to chemical substances       0.00      0.00      0.00         7
Exposure to extreme temperatures       0.00      0.00      0.00         4
                           Falls       0.52      0.88      0.66        49
            Fires and explosions       1.00      0.33      0.50        15
        St

In [144]:
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest, chi2
import pickle

In [145]:
from sklearn.linear_model import LogisticRegression
X= data['summary.new']
Y = data['Tagged2']
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, Y, test_size=0.2)

In [146]:
pipeline = Pipeline([('vect', v),
                     ('chi',  SelectKBest(chi2, k=1200)),
                     ('clf', LogisticRegression(random_state=0))])



In [147]:
model = pipeline.fit(X_train, y_train)
with open('LogisticRegression.pickle', 'wb') as f:
    pickle.dump(model, f)


In [148]:
ytest = np.array(y_test)

In [149]:
print(classification_report(ytest, model.predict(X_test)))
print(confusion_matrix(ytest, model.predict(X_test)))



                                  precision    recall  f1-score   support

       caught in/between objects       1.00      0.19      0.32        16
              collapse of object       0.40      0.68      0.50        40
                   electrocution       1.00      0.87      0.93        23
 exposure to chemical substances       0.00      0.00      0.00         6
exposure to extreme temperatures       0.00      0.00      0.00         4
                           falls       0.60      0.89      0.72        53
             fires and explosion       1.00      0.20      0.33         5
                          others       0.00      0.00      0.00         7
        struck by falling object       0.00      0.00      0.00        10
        struck by moving objects       0.61      0.58      0.60        24
                         traffic       0.50      0.33      0.40        12

                       micro avg       0.58      0.58      0.58       200
                       macro avg    

In [203]:
import random
best=-100000
populations = [random.randint(0.0,1.0) for x in range(6)] 
print(type(populations))
parents=[]
new_populations = []
print(populations)

<type 'list'>
[1, 0, 1, 0, 1, 0]
